-- Vocation system upgrade: add job metadata columns, create check-ins table, add RLS

-- 1. Extend vocation table
alter table "public"."vocation"
  add column if not exists "contact_name" text default '',
  add column if not exists "contact_phone" text default '',
  add column if not exists "days_of_week" integer[] default '{}',
  add column if not exists "assigned_by" uuid references public.users(id),
  add column if not exists "is_active" boolean not null default true;

-- 2. Check-in log table
create table if not exists "public"."vocation_checkins" (
  "id" bigint generated by default as identity not null primary key,
  "created_at" timestamp with time zone not null default now(),
  "vocation_id" bigint not null references public.vocation(id) on delete cascade,
  "user_id" uuid not null references public.users(id),
  "checkin_date" date not null default current_date,
  "hours" numeric(4,2) default null,
  "note" text default '',
  "is_retroactive" boolean not null default false,
  constraint uq_user_date unique (user_id, checkin_date)
);

-- 3. RLS on vocation table
alter table "public"."vocation" enable row level security;

-- Drop any existing permissive policies first (table previously had no policies)
drop policy if exists "students_read_own_vocation" on public.vocation;
drop policy if exists "vocation_staff_read_all" on public.vocation;
drop policy if exists "vocation_staff_insert" on public.vocation;
drop policy if exists "vocation_staff_update" on public.vocation;

create policy "students_read_own_vocation" on public.vocation
  for select using (user_id = auth.uid());

create policy "vocation_staff_read_all" on public.vocation
  for select using (
    exists (
      select 1 from public.users u
      join public.user_profiles up on up.id = u.id
      where u.id = auth.uid()
        and u.role = 'staff'
        and up.title ilike '%תעסוקה%'
    )
  );

create policy "vocation_staff_insert" on public.vocation
  for insert with check (
    exists (
      select 1 from public.users u
      join public.user_profiles up on up.id = u.id
      where u.id = auth.uid()
        and u.role = 'staff'
        and up.title ilike '%תעסוקה%'
    )
  );

create policy "vocation_staff_update" on public.vocation
  for update using (
    exists (
      select 1 from public.users u
      join public.user_profiles up on up.id = u.id
      where u.id = auth.uid()
        and u.role = 'staff'
        and up.title ilike '%תעסוקה%'
    )
  );

-- 4. RLS on vocation_checkins
alter table "public"."vocation_checkins" enable row level security;

create policy "students_manage_own_checkins" on public.vocation_checkins
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "vocation_staff_read_all_checkins" on public.vocation_checkins
  for select using (
    exists (
      select 1 from public.users u
      join public.user_profiles up on up.id = u.id
      where u.id = auth.uid()
        and u.role = 'staff'
        and up.title ilike '%תעסוקה%'
    )
  );

-- Grant access to authenticated users (consistent with rest of schema)
grant all on public.vocation_checkins to anon, authenticated, service_role;
grant usage, select on sequence vocation_checkins_id_seq to anon, authenticated, service_role;
